name: Gradle generate and publish multi-project javadocs

on:
  workflow_call:
    inputs:
      projects:
        description: 'names of the projects separated by new line'
        default: 'api'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate javadoc
        run: './gradlew javadoc'
      - name: shell
        run: |
          mkdir ./javadoc
          IFS='
          '
          projects="${{ inputs.projects }}"
          for project in $projects; do
            cp -r "$project/build/docs/javadoc" "./javadoc/$project"
          done
      - name: Deploy github pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: javadocs
          folder: javadoc
